version: '3'
services:
  mysql-server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: midb
    ports:
      - "3306:3306"
    networks:
      - app-net

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql-server
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
